export const PatientData = [
    {
        id: 6532,
        name: 'Paul Edikan',
        age: 20,
        gender: 'Male',
        height: '1.8m',
        weight: '65kg',
        bloodGroup: 'O+',
        billed: 20000,
        treatment: 'Malaria',
        note: 'Has been prescribed drugs',
        appointmentDate: '20/05/2024',
        status: 'pending',
        test: 'blood dialysis',
        results: 'negative',
        doctor: 'Dr. Ogunkoya',
    },
    {
        id: 7421,
        name: 'John Doe',
        age: 18,
        gender: 'Male',
        height: '1.92m',
        weight: '74kg',
        bloodGroup: 'AB+',
        billed: 10000,
        treatment: 'Thyphoid',
        note: 'Has been prescribed drugs',
        appointmentDate: '22/05/2024',
        status: 'completed',
        test: 'blood dialysis',
        results: 'positive',
        doctor: 'Dr. Naomi',
    },
    {
        id: 6291,
        name: 'Paul Edikan',
        age: 22,
        gender: 'Female',
        height: '1.6m',
        weight: '62kg',
        bloodGroup: 'B-',
        billed: 17000,
        treatment: 'Constipation',
        note: 'Awaiting further tests',
        appointmentDate: '20/05/2024',
        status: 'waiting',
        test: 'blood dialysis',
        results: 'pending',
        doctor: 'Dr. Ogunkoya',
    },
]